errors:
  disabled: 禁用工作流或触发器
  handleNotUnique: 工作流句柄不是唯一的
  invalidHandle: 无效的句柄
  invalidID: 无效的 ID
  notAllowedToCreate: 不允许创建工作流
  notAllowedToDelete: 不允许删除此工作流
  notAllowedToExecute: 不允许执行此工作流
  notAllowedToExecuteCorredorStep: 不允许运行 corredorExec 函数，corredor 被禁用
  notAllowedToRead: 不允许读取此工作流
  notAllowedToSearch: 不允许搜索或列出工作流
  notAllowedToUndelete: 不允许取消删除此工作流
  notAllowedToUpdate: 不允许更新此工作流
  notFound: 未找到工作流
  staleData: 陈旧数据
  unknownWorkflowStep: 未知的工作流程步骤
