errors:
  invalidID: 无效的 ID
  notAllowedToCreate: 不允许创建应用程序
  notAllowedToDelete: 不允许删除此应用程序
  notAllowedToManageFlag: 不允许管理应用程序的标志
  notAllowedToManageFlagGlobal: 不允许管理应用程序的全局标志
  notAllowedToRead: 不允许读取此应用程序
  notAllowedToSearch: 不允许搜索或列出应用程序
  notAllowedToUndelete: 不允许取消删除此应用程序
  notAllowedToUpdate: 不允许更新此应用程序
  notFound: 未找到应用程序
